DROP TABLE if exists USERTEAMS cascade;
DROP TABLE if exists PERMTYPES cascade; 
DROP TABLE if exists COSTTYPES cascade; 
DROP TABLE if exists STATUSTYPES cascade; 
DROP TABLE if exists USERS cascade;
DROP TABLE if exists REGISTERS cascade;

CREATE TABLE USERTEAMS(
	ID serial PRIMARY KEY,
	TEAMNAME varchar(255) UNIQUE
);
 CREATE TABLE PERMTYPES(
	ID serial PRIMARY KEY,
	PERMNAME varchar(250) UNIQUE
);

CREATE TABLE COSTTYPES(
	ID serial PRIMARY KEY,
	COSTNAME varchar(250) UNIQUE
);

CREATE TABLE STATUSTYPES(
	ID serial PRIMARY KEY,
	STATUSNAME varchar(250) UNIQUE
	);

CREATE TABLE USERS(
   ID serial PRIMARY KEY,
   NAME varchar(255),
   SURNAME varchar(255),
   EMAIL varchar(255) UNIQUE ,
   TEAM_ID int  REFERENCES USERTEAMS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
   PASSWORD varchar(255),
   PERM_TYPE_ID int REFERENCES PERMTYPES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
   USERROLE numeric,
   USERLOG numeric
);

CREATE TABLE REGISTERS(
	ID serial PRIMARY KEY,
	TAG varchar(255),
	CFP varchar(255),
	FTID varchar(255),
	JIRATASK varchar(255),
	CREATE_USER_ID int NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	UPDATE_USER_ID int REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	COST_ID int  NOT NULL REFERENCES COSTTYPES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	STARTDATE date NOT NULL,
	FINISHDATE date	
);

select *from USERTEAMS;
select *from PERMTYPES;
select *from COSTTYPES;
select *from STATUSTYPES;
select *from USERS;
select *from REGISTERS;

